feat: modernize workflows (#219)
* feat: update dependabot workflow to issue deprecation warning

* feat: add deprecation warning to cancel workflow

* feat: add pull request types to lint workflow trigger

Allowing lint-pr to be trigerred through a ruleset on the org level

* docs: add deprecation warnings for cancel-workflow and dependabot actions in README

* ci: restructure and secure workflows

* style: fix code format

* docs: update deprecation warnings for dependabot workflow and action

BREAKING CHANGE: dependabot workflow is no longer taking action

diff --git a/.github/workflows/dependabot.yml b/.github/workflows/dependabot.yml
--- a/.github/workflows/dependabot.yml
+++ b/.github/workflows/dependabot.yml
@@ -21,28 +21,32 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.actor == 'dependabot[bot]' }}
     steps:
-      - name: Dependabot metadata
-        id: metadata
-        uses: dependabot/fetch-metadata@v2
-        with:
-          github-token: '${{ secrets.GITHUB_TOKEN }}'
+      - name: warning
+        shell: bash
+        run: |
+          echo "::warning title=Deprecated::Dependabot automation workflow is being replaced through AutoMate App you can remove this call from your workflow"
+      # - name: Dependabot metadata
+      #   id: metadata
+      #   uses: dependabot/fetch-metadata@v2
+      #   with:
+      #     github-token: '${{ secrets.GITHUB_TOKEN }}'
 
-      - name: Enable auto-merge for Dependabot PRs
-        continue-on-error: true
-        # if: ${{contains(steps.metadata.outputs.dependency-names, '') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
-        # Auto merge all dependencies with patch or minor version updates
-        if: ${{(steps.metadata.outputs.update-type == 'version-update:semver-patch') || (steps.metadata.outputs.update-type == 'version-update:semver-minor')}}
-        run: gh pr merge --auto --squash "$PR_URL"
-        env:
-          PR_URL: ${{github.event.pull_request.html_url}}
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }} # GH_TOKEN needed to trigger follow up worlflow: https://github.com/fastify/github-action-merge-dependabot/issues/134
+      # - name: Enable auto-merge for Dependabot PRs
+      #   continue-on-error: true
+      #   # if: ${{contains(steps.metadata.outputs.dependency-names, '') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
+      #   # Auto merge all dependencies with patch or minor version updates
+      #   if: ${{(steps.metadata.outputs.update-type == 'version-update:semver-patch') || (steps.metadata.outputs.update-type == 'version-update:semver-minor')}}
+      #   run: gh pr merge --auto --squash "$PR_URL"
+      #   env:
+      #     PR_URL: ${{github.event.pull_request.html_url}}
+      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }} # GH_TOKEN needed to trigger follow up worlflow: https://github.com/fastify/github-action-merge-dependabot/issues/134
 
-      - name: Approve a PR
-        continue-on-error: true
-        run: gh pr review --approve "$PR_URL"
-        env:
-          PR_URL: ${{github.event.pull_request.html_url}}
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }} # GH_TOKEN needed to approve PR as code owner on protected branches
+      # - name: Approve a PR
+      #   continue-on-error: true
+      #   run: gh pr review --approve "$PR_URL"
+      #   env:
+      #     PR_URL: ${{github.event.pull_request.html_url}}
+      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }} # GH_TOKEN needed to approve PR as code owner on protected branches
 
-      - name: '🧹 Cleanup workspace'
-        uses: eviden-actions/clean-self-hosted-runner@v1
+      # - name: '🧹 Cleanup workspace'
+      #   uses: eviden-actions/clean-self-hosted-runner@v1
